name: Build and Release Sync Tool

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          copy ignored_extensions.json dist\
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-windows
          path: dist/*

  build-linux:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          cp ignored_extensions.json dist/
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-linux
          path: dist/*

  build-macos-intel:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          cp ignored_extensions.json dist/
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-macos-intel
          path: dist/*

  build-macos-applesilicon:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          cp ignored_extensions.json dist/
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-macos-applesilicon
          path: dist/*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-windows, build-linux, build-macos-intel, build-macos-applesilicon]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show artifact structure (debug)
        run: find artifacts

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release with Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.ref_name }}
          RELEASE_NAME="Release $TAG_NAME"

          gh release create "$TAG_NAME" \
            "artifacts/one-to-many-windows/ui_copy_tool.exe#ui_copy_tool-windows.exe" \
            "artifacts/one-to-many-linux/ui_copy_tool#ui_copy_tool-linux" \
            "artifacts/one-to-many-macos-intel/ui_copy_tool#ui_copy_tool-macos-intel" \
            "artifacts/one-to-many-macos-applesilicon/ui_copy_tool#ui_copy_tool-macos-applesilicon" \
            --title "$RELEASE_NAME" \
            --notes "Automated release for $TAG_NAME"
