name: Build and Release Sync Tool

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          copy ignored_extensions.json dist\
          Compress-Archive -Path dist\* -DestinationPath one-to-many-windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-windows
          path: one-to-many-windows.zip

  build-linux:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          cp ignored_extensions.json dist/
          zip -r one-to-many-linux.zip dist/
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-linux
          path: one-to-many-linux.zip

  build-macos-intel:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          cp ignored_extensions.json dist/
          zip -r one-to-many-macos-intel.zip dist/
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-macos-intel
          path: one-to-many-macos-intel.zip

  build-macos-applesilicon:
    if: github.ref_type == 'tag' || github.ref_name == 'develop'
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed ui_copy_tool.py
          cp ignored_extensions.json dist/
          zip -r one-to-many-macos-applesilicon.zip dist/
      - uses: actions/upload-artifact@v4
        with:
          name: one-to-many-macos-applesilicon
          path: one-to-many-macos-applesilicon.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build-windows
      - build-linux
      - build-macos-intel
      - build-macos-applesilicon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifact contents (debug)
        run: find artifacts

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release with Zipped Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.ref_name }}
          RELEASE_NAME="Release $TAG_NAME"

          gh release create "$TAG_NAME" \
            "artifacts/one-to-many-windows/one-to-many-windows.zip#ui_copy_tool-windows.zip" \
            "artifacts/one-to-many-linux/one-to-many-linux.zip#ui_copy_tool-linux.zip" \
            "artifacts/one-to-many-macos-intel/one-to-many-macos-intel.zip#ui_copy_tool-macos-intel.zip" \
            "artifacts/one-to-many-macos-applesilicon/one-to-many-macos-applesilicon.zip#ui_copy_tool-macos-applesilicon.zip" \
            --title "$RELEASE_NAME" \
            --notes "Automated release for $TAG_NAME"
